In [37]:

import os
import cv2
from IPython.display import display_html, display
from PIL import Image as PILImage
# from utils import display_borderless_tables

from img2table.document import Image
from img2table.ocr import TesseractOCR, PaddleOCR

In [38]:
img = Image("table_image.jpg")
tesseract = TesseractOCR()

# Extract tables with Tesseract and PaddleOCR
tables = img.extract_tables(ocr=tesseract, borderless_tables=True)

df = tables[0].df
print(df)

                               0                                1  \
0                           None  Land and\nbuildings\nowned\nR'm
1              Carrying value at                             None
2                 1 October 2020                             6711
3                      Additions                               88
4            on\nof subsidiaries                              167
5         Disposal of subsidiary                            (184)
6       Disposals, scrappings or                             None
7                 derecoanitions                             None
8                      Transfers                             None
9    Borrowing costs capitalised                                8
10  Depreciation from continuing                             None
11                    operations                            (183)
12        discontinued operation                               ()
13    Effect of foreign currency                             None
14                      movement                            (113)
15             Carrying value at                             None
16             30 September 2021                            6 688

                               2                                    3  \
0   Fixed\nproperty\nleased\nR'm  Improve-\nments to\nuse assets\nRim
1                           None                                 None
2                           None                                 None
3                           None                                   49
4                           None                                    2
5                           None                                (134)
6                           None                                 None
7                           None                                  (3)
8                           None                                   84
9                           None                                 None
10                          None                                 None
11                          None                                (133)
12                          None                                   2)
13                          None                                 None
14                          None                                 (24)
15                          None                                 None
16                          None                                  880

                          4                                           5  \
0   Medical\nequipment\nR'm  Motor\nvehicles\nand other\nequipment\nR'm
1                      None                                        None
2                      3379                                         602
3                       627                                          97
4                         3                                          12
5                     (189)                                        (13)
6                      None                                        None
7                      (22)                                        (14)
8                      None                                         147
9                      None                                        None
10                     None                                        None
11                    (726)                                       (167)
12                      (4)                                          ()
13                     None                                        None
14                    (176)                                        (14)
15                     None                                        None
16                     3209                                         655

                              6                                    7  \
0   Right-\nof-use\nassets\nRim  Assets\nunder\nconstruc-\ntion\nR'm
1                          None                                 None
2                          3077                                  481
3                           701                                  965
4                          None                                    -
5                          None                                 (21)
6                          None                                 None
7                          (65)                                 None
8                           185                                 None
9                          None                                 None
10                         None                                 None
11                        (362)                                 None
12                         (13)                                 None
13                         None                                 None
14                        (216)                                 (40)
15                         None                                 None
16                         2827                                  436

             8
0   Total\nR'm
1         None
2        15361
3         2527
4          184
5      (1 021)
6         None
7        (104)
8         (21)
9           14
10        None
11      (1574)
12        (21)
13        None
14       (653)
15        None
16      14.695

In [39]:
# Extract the first column as an array (list) except the header
first_column = df.iloc[0:, 0].values
# print(first_column)
#remove the first element
first_column = first_column[1:]
print(first_column)

['Carrying value at' '1 October 2020' 'Additions' 'on\nof subsidiaries'
 'Disposal of subsidiary' 'Disposals, scrappings or' 'derecoanitions'
 'Transfers' 'Borrowing costs capitalised' 'Depreciation from continuing'
 'operations' 'discontinued operation' 'Effect of foreign currency'
 'movement' 'Carrying value at' '30 September 2021']

In [40]:
import pandas as pd

# Convert the table to a DataFrame
table_df = pd.DataFrame(tables[0].df)

# Now you can work with 'table_df' as a DataFrame
print(table_df)

                               0                                1  \
0                           None  Land and\nbuildings\nowned\nR'm
1              Carrying value at                             None
2                 1 October 2020                             6711
3                      Additions                               88
4            on\nof subsidiaries                              167
5         Disposal of subsidiary                            (184)
6       Disposals, scrappings or                             None
7                 derecoanitions                             None
8                      Transfers                             None
9    Borrowing costs capitalised                                8
10  Depreciation from continuing                             None
11                    operations                            (183)
12        discontinued operation                               ()
13    Effect of foreign currency                             None
14                      movement                            (113)
15             Carrying value at                             None
16             30 September 2021                            6 688

                               2                                    3  \
0   Fixed\nproperty\nleased\nR'm  Improve-\nments to\nuse assets\nRim
1                           None                                 None
2                           None                                 None
3                           None                                   49
4                           None                                    2
5                           None                                (134)
6                           None                                 None
7                           None                                  (3)
8                           None                                   84
9                           None                                 None
10                          None                                 None
11                          None                                (133)
12                          None                                   2)
13                          None                                 None
14                          None                                 (24)
15                          None                                 None
16                          None                                  880

                          4                                           5  \
0   Medical\nequipment\nR'm  Motor\nvehicles\nand other\nequipment\nR'm
1                      None                                        None
2                      3379                                         602
3                       627                                          97
4                         3                                          12
5                     (189)                                        (13)
6                      None                                        None
7                      (22)                                        (14)
8                      None                                         147
9                      None                                        None
10                     None                                        None
11                    (726)                                       (167)
12                      (4)                                          ()
13                     None                                        None
14                    (176)                                        (14)
15                     None                                        None
16                     3209                                         655

                              6                                    7  \
0   Right-\nof-use\nassets\nRim  Assets\nunder\nconstruc-\ntion\nR'm
1                          None                                 None
2                          3077                                  481
3                           701                                  965
4                          None                                    -
5                          None                                 (21)
6                          None                                 None
7                          (65)                                 None
8                           185                                 None
9                          None                                 None
10                         None                                 None
11                        (362)                                 None
12                         (13)                                 None
13                         None                                 None
14                        (216)                                 (40)
15                         None                                 None
16                         2827                                  436

             8
0   Total\nR'm
1         None
2        15361
3         2527
4          184
5      (1 021)
6         None
7        (104)
8         (21)
9           14
10        None
11      (1574)
12        (21)
13        None
14       (653)
15        None
16      14.695

In [ ]:
#check for all row if the value is empty except the first column
for row in table_df.iterrows():